#!/usr/bin/env bash

set -e

install_package zsh

chsh -s $(which zsh)

echo "Installing Oh My Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

install_config zshrc
link_config_to_dotfile zshrc
